/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e2e2e5",
        "on-tertiary-fixed": "#241a00",
        "surface-variant": "#333537",
        "on-error": "#690005",
        "surface-container-lowest": "#0c0e10",
        "on-tertiary": "#3c2f00",
        "surface-container": "#1e2022",
        "tertiary-fixed": "#ffe088",
        "primary-container": "#2962ff",
        "secondary-container": "#374c56",
        "surface-tint": "#b6c4ff",
        "on-secondary-fixed-variant": "#354a53",
        "surface-dim": "#121416",
        "on-secondary": "#1e333c",
        "primary-fixed": "#dce1ff",
        "on-tertiary-fixed-variant": "#574500",
        "on-tertiary-container": "#4f3d00",
        "surface-bright": "#38393c",
        "on-secondary-container": "#a6bcc7",
        "outline-variant": "#434656",
        "on-secondary-fixed": "#071e27",
        "on-primary-container": "#f7f5ff",
        "on-background": "#e2e2e5",
        "error": "#ffb4ab",
        "tertiary-container": "#cca730",
        "outline": "#8d90a2",
        "surface-container-low": "#1a1c1e",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#003ab3",
        "inverse-on-surface": "#2f3133",
        "secondary-fixed": "#cfe6f2",
        "tertiary-fixed-dim": "#e9c349",
        "on-primary": "#002780",
        "surface-container-highest": "#333537",
        "on-surface-variant": "#c3c5d8",
        "inverse-primary": "#004ee8",
        "on-primary-fixed": "#001550",
        "tertiary": "#e9c349",
        "primary": "#b6c4ff",
        "on-surface": "#e2e2e5",
        "secondary-fixed-dim": "#b4cad6",
        "surface": "#121416",
        "primary-fixed-dim": "#b6c4ff",
        "background": "#121416",
        "secondary": "#b4cad6",
        "surface-container-high": "#282a2c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
